# Generated by Django 4.0.6 on 2022-07-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(verbose_name='Полное наименование')),
                ('short_name', models.TextField(blank=True, null=True, verbose_name='Сокращенное наименование')),
                ('inn', models.CharField(blank=True, db_index=True, max_length=10, null=True, verbose_name='ИНН')),
                ('ogrn', models.CharField(db_index=True, max_length=13, unique=True, verbose_name='ОГРН')),
                ('factual_address', models.TextField(verbose_name='Адрес')),
                ('region_code', models.CharField(max_length=3, null=True, verbose_name='Код региона')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['full_name'],
            },
        ),
    ]
