# Generated by Django 4.0.6 on 2023-09-17 18:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('organizations', '0002_create_fts_schema'),
    ]

    operations = [
        migrations.RunSQL(
            sql='''
            CREATE TRIGGER organizations_update_trigger
            BEFORE INSERT OR UPDATE OF full_name, short_name, full_name_search
            ON organizations_organization
            FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(
              full_name_search, 'public.russian_egrul', full_name, short_name);

            UPDATE organizations_organization SET full_name_search = NULL;
            ''',

            reverse_sql='''
            DROP TRIGGER IF EXISTS organizations_update_trigger
            ON organizations_organization;
            '''),
    ]
