# Generated by Django 4.0.6 on 2022-12-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_trigger_on_fts'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='kpp',
            field=models.CharField(blank=True, db_index=True, max_length=9, null=True, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='ogrn',
            field=models.CharField(db_index=True, max_length=13, verbose_name='ОГРН'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(fields=('inn', 'ogrn', 'kpp'), name='unique_organization'),
        ),
    ]
