# Generated by Django 4.0.6 on 2023-09-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_create_fts_trigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='EgrulVersion',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('version', models.DateField()),
            ],
            options={
                'db_table': 'egrul_version',
            },
        ),
    ]
