# Generated by Django 4.0.6 on 2023-03-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organization_kpp_alter_organization_ogrn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
