# Generated by Django 4.0.6 on 2023-10-02 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_added_egrul_version'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='organization',
            name='unique_organization',
        ),
    ]
