# Generated by Django 4.0.6 on 2023-12-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_remove_organization_unique_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_main',
            field=models.BooleanField(default=True, help_text='Основная ли организация?', verbose_name='Основная'),
        ),
    ]
