# Generated by Django 4.0.6 on 2023-12-08 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_remove_organization_unique_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='main',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='organizations.organization'),
        ),
    ]
