name: egrul_fts_api Workflow

on: [push]

jobs:

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]

    steps:
    - uses: actions/checkout@v3
    - name: Setting up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Installing dependencies
      run: | 
        python -m pip install --upgrade pip 
        pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
        pip install -r egrul/requirements.txt
    - name: Testing with flake8
      run: |
        # запуск проверки проекта по flake8
        python -m flake8
    - name: Testing with pytest
      run: |
        # запуск проверки проекта pytest
        python -m pytest
